### ISSUE TITLE
get error

### ISSUE THREAD

**Issue by dionkuarta97** [heroims/react-native-web3-wallet#11]
i get this error when using function createWallet

<img width="317" alt="image" src="https://user-images.githubusercontent.com/73380930/235353693-f348d3d1-dc9a-42c5-ba6c-0f10eecba710.png">

i get error on hdnode

<img width="556" alt="image" src="https://user-images.githubusercontent.com/73380930/235358433-b761f13e-5b53-4115-ba87-f0181bf09119.png">

<img width="394" alt="image" src="https://user-images.githubusercontent.com/73380930/235358467-4f17675c-c4ce-4a25-84c1-f2960862f337.png">

**Comment by dionkuarta97** [comment]
> you need install patches

i have already install

**Comment by heroims** [comment]
> > you need install patches
> 
> i have already install

Your screenshot indicates that the patches were not installed and the method not being found is likely due to issues with your use of ethers in many of your operations
