### ISSUE TITLE
TypeError: node.derivePath is not a function error

### ISSUE THREAD

**Issue by suatozkan** [heroims/react-native-web3-wallet#12]
Hi, I started to get "TypeError: node.derivePath is not a function" error when I create wallet. Patches and additional libraries are installed but I could not fix it? Do you have any advice?

**Comment by heroims** [comment]
Check the current installed version of ethers. The released version targets version 5.x. Your issue is clearly that the ethers method cannot be found. For version 6.x, refer to my [ethers6.x branch](https://github.com/heroims/react-native-web3-wallet/tree/ether6.x).
