### ISSUE TITLE
Error : JsonRpcProvider failed to detect network and cannot start up; retry in 1s (perhaps the URL is wrong or the node is not started)

### ISSUE THREAD

**Issue by jibo001** [heroims/react-native-web3-wallet#14]
why i get this error when i use this package , but i can get right data from this package;
<img width="939" alt="image" src="https://github.com/heroims/react-native-web3-wallet/assets/56509810/650c6eb5-2022-49ce-9e32-fe59a3b465ad">
<img width="593" alt="image" src="https://github.com/heroims/react-native-web3-wallet/assets/56509810/5eb71550-b776-4584-b8f7-19824689bf7d">

**Comment by heroims** [comment]
https://github.com/ethers-io/ethers.js/issues/4377
