### ISSUE TITLE
Patching not working "react-native-aes-crypto"

### ISSUE THREAD

**Issue by Coding-Algorithm** [heroims/react-native-web3-wallet#6]
Hi.

I followed your guideline on using your package, but I hit a roadblock at around the third stage.

Patch not working for "react-native-aes-crypto".

Here is the response after running the patch command...

> `patch-package 6.4.7
Applying patches...
@ethersproject/hdnode@5.7.0 ✔
@ethersproject/json-wallets@5.7.0 ✔
@ethersproject/wallet@5.7.0 ✔
react-native-scrypt@1.2.1 ✔
react-native-web3-wallet@1.2.0 ✔

**ERROR** Failed to apply patch for package react-native-aes-crypto at path
  
    node_modules/react-native-aes-crypto

  This error was caused because react-native-aes-crypto has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run 

    patch-package react-native-aes-crypto

  Info:
    Patch file: patches/react-native-aes-crypto+2.1.0.patch
    Patch was made for version: 2.1.0
    Installed version: 2.1.1

---
patch-package finished with 1 error(s).`

**Comment by heroims** [comment]
npm install react-native-aes-crypto@2.1.0
